### ISSUE TITLE
Interpolating llc output to a regular lat-lon grid

### ISSUE THREAD

**Issue by amrhein** [gaelforget/gcmfaces#8]
Is there a routine for interpolating llc output (both 2d and 3d) to a regular lat-lon grid? Thanks!

**Comment by timothyas** [comment]
Hey @amrhein, there may be a better way, but at least for plotting you can check out  `gcmfaces_convert/convert2pcol.m` will get you started. For gcmfaces objects on a LLC grid it will convert the field to a lat/lon array which can then be plotted easily, with the help of the `m_map` function `m_ll2xy`. See for instance 
My guess is that this is only for 2D fields because it's a routine designed for plotting, but it's at least a breadcrumb trail. I also know of how to do this in python which I'm using predominantly these days, so if you're interested in that feel free to ping me!

**Comment by gaelforget** [comment]
Interpolation capabilities are illustrated in `sample_processing/example_interp.m` as mentioned in the manual in [tutorial examples](https://gcmfaces.readthedocs.io/en/latest/prep_demo.html). Would be good to turn these examples into notebooks but have not found time to do it...

Does `gcmfaces_interp_2d.m` do what you need? 

The example shows how you can speed it up by computing the interpolation coefficients just once.

The `convert2pcol.m` code mentioned by @timothyas (thanks) is not really interpolation but rather reorganizing data so that pcolor looks good pole to pole. For the lat-lon part of the grid, it's basically the same as [eccov4_latlon.m](https://gist.github.com/gaelforget/224e4ffe3da9816926f5e3b3e288e8db).

**Comment by timothyas** [comment]
Thanks @gaelforget! So, now I'm curious, is there interpolation in the `m_ll2xy.m` function or is this simply a scaling to "x/y units" for plotting? I always thought there was some type of interpolation going on for plotting (other than if e.g. for pcolor the user chooses `shading interp`).

**Comment by gaelforget** [comment]
@timothyas `m_ll2xy.m` is from `m_map` and we merely overload it for the `gcmfaces` type. You would have to look into the `m_map` code (or maybe its help or doc) to be sure, but I believe that this function just changes coordinate system without involving any interpolation.

**Comment by timothyas** [comment]
I see, thanks @gaelforget! 

(yep taking a quick look at `m_ll2xy` it seems that way)

**Comment by amrhein** [comment]
Thanks @gaelforget <https://github.com/gaelforget> and @timothyas
<https://github.com/timothyas>! Yes, gcmfaces_interp_2d.m does the trick.
Tim, I might be in touch about those python routines at some point, thanks
for offering.

**Comment by gaelforget** [comment]
Great! So, I am closing this issue
